version: 2.1

jobs:
  test:
    docker:
      - image: "cimg/go:1.16"
    steps:
      - checkout
      - restore_cache:
          keys:
            - v3-{{ checksum "go.mod" }}-{{ .Branch }}
            - v3-{{ checksum "go.mod" }}-
            - v3-
      - run: go generate
      - run: .gobincache/golangci-lint run
      - run: go test -race ./...
      - run: .gobincache/goveralls -service=CircleCI
      - save_cache:
          when: always
          key: v3-{{ checksum "go.mod" }}-{{ .Branch }}
          paths:
            - ~/go/bin/
            - ~/go/pkg/
            - ~/go/src/
            - ~/.cache/go-build/
            - ~/.cache/golangci-lint/
            - .gobincache/

workflows:
  default:
    jobs:
      - test
