name: CI/CD

on:
  push:
    branches: master
    tags: v*
  pull_request:
    branches: master

env:
  GO_VERSION: '^1.19'

jobs:

  test:
    runs-on: 'ubuntu-latest'
    timeout-minutes: 30
    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: ${{ env.GO_VERSION }}

      - uses: actions/checkout@v3

      - uses: actions/cache@v3
        with:
          path: |
            ~/go/bin
            ~/go/pkg
            ~/go/src
            ~/.cache/go-build
            ~/.cache/golangci-lint
            .buildcache
          key: v4-test-${{ runner.os }}-${{ hashFiles('go.mod') }}
          restore-keys: |
            v4-test-${{ runner.os }}-

      - run: go generate
      - run: .buildcache/bin/golangci-lint run
      - run: go test -race ./...

      - name: Report code coverage
        env:
          COVERALLS_TOKEN: ${{ secrets.COVERALLS_TOKEN }}
        if: env.COVERALLS_TOKEN
        run: .buildcache/bin/goveralls -service=GitHub
